# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vote_window(object):
    john = 0
    jane = 0

    def open_results(self):
        self.window_results = QtWidgets.QWidget()
        self.ui_results = Ui_result_window()
        self.ui_results.setupUi(self.window_results)
        self.window_results.show()

    def exit(self):
        vote_window.close()

    def john(self):
        self.john += 1
        return self.john

    def jane(self):
        self.jane += 1
        return self.jane

    def setupUi(self, vote_window):
        vote_window.setObjectName("vote_window")
        vote_window.resize(252, 116)
        vote_window.setMaximumSize(QtCore.QSize(252, 116))
        vote_window.setWindowTitle("")
        self.candidates_label = QtWidgets.QLabel(vote_window)
        self.candidates_label.setGeometry(QtCore.QRect(90, 20, 71, 16))
        self.candidates_label.setObjectName("candidates_label")
        self.john_label = QtWidgets.QLabel(vote_window)
        self.john_label.setGeometry(QtCore.QRect(40, 40, 31, 16))
        self.john_label.setObjectName("john_label")
        self.jane_label = QtWidgets.QLabel(vote_window)
        self.jane_label.setGeometry(QtCore.QRect(170, 40, 31, 16))
        self.jane_label.setObjectName("jane_label")
        self.john_vote = QtWidgets.QPushButton(vote_window, clicked = lambda: self.john())
        self.john_vote.setGeometry(QtCore.QRect(10, 70, 93, 28))
        self.john_vote.setObjectName("john_vote")
        self.vote_group = QtWidgets.QButtonGroup(vote_window)
        self.vote_group.setObjectName("vote_group")
        self.vote_group.addButton(self.john_vote)
        self.jane_vote = QtWidgets.QPushButton(vote_window, clicked = lambda: self.jane())
        self.jane_vote.setGeometry(QtCore.QRect(140, 70, 93, 28))
        self.jane_vote.setObjectName("jane_vote")
        self.vote_group.addButton(self.jane_vote)

        self.retranslateUi(vote_window)
        QtCore.QMetaObject.connectSlotsByName(vote_window)

    def retranslateUi(self, vote_window):
        _translate = QtCore.QCoreApplication.translate
        self.candidates_label.setText(_translate("vote_window", "Candidates"))
        self.john_label.setText(_translate("vote_window", "John"))
        self.jane_label.setText(_translate("vote_window", "Jane"))
        self.john_vote.setText(_translate("vote_window", "Vote John"))
        self.jane_vote.setText(_translate("vote_window", "Vote Jane"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vote_window = QtWidgets.QWidget()
    ui = Ui_vote_window()
    ui.setupUi(vote_window)
    vote_window.show()
    sys.exit(app.exec_())